# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9db8cd0e47ff0b36efe03ca6cb4196d56255430a111a4b192e2f0b36c0e43ccc1f6fa2bd4574b93f7ba2dc8e7f17ebe0f778f00dc24e62185d67730510b796

test:
  secret_key_base: 53dc3ce0b51f4e7ad6796e4ed155d9e4819944199aaa349dd2837456adbed1f218bc16ee2fff4066281018c26bdc9ad8df7c39346a5cc90ae07e93bb31539964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
